[test_dialer_airplane_mode.py]
[test_dialer.py]
carrier = true
[test_MMI.py]
carrier = true
[test_dialer_add_contact.py]
# Bug 855039 -  Adding a contact via dialer - phone number is not saved against the contact
xfail = true
carrier = true
